// scripts/rebrand.mjs
// Fork rebrand: rewrites user-visible "Anarlog" strings to "Recap" across
// the desktop app source. Idempotent — safe to re-run after upstream merges.
// Never touches: import/require lines, lowercase functional ids/URLs,
// crates/, plugins/, package names.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const TARGET_DIR = join(ROOT, "apps/desktop/src");
const CHECK = process.argv.includes("--check");

const BRAND_FROM = "Anarlog";
const BRAND_TO = "Recap";

const isModuleContextLine = (line) =>
  /^\s*(import|export)\b/.test(line) || // import/export statement starts
  /\bfrom\s*["']/.test(line) || // ...} from "path" continuations
  /\bimport\s*\(/.test(line) || // dynamic import()
  /\brequire\s*\(/.test(line); // require()

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) {
      if (name === "locales") continue; // regenerated by lingui, not edited
      yield* walk(p);
    } else if (/\.(ts|tsx)$/.test(name)) {
      yield p;
    }
  }
}

let changed = 0;
const refusals = [];
const rebrandables = [];

for (const file of walk(TARGET_DIR)) {
  const src = readFileSync(file, "utf8");
  if (!src.includes(BRAND_FROM)) continue;

  const out = src
    .split("\n")
    .map((line, i) => {
      if (!line.includes(BRAND_FROM)) return line;

      const isModuleContext = isModuleContextLine(line);

      if (isModuleContext) {
        // Split on quoted strings: odd indices are quoted, even are unquoted.
        // Refuse if BRAND_FROM appears in a quoted module path.
        const segments = line.split(/("[^"]*"|'[^']*')/);
        let refused = false;

        const transformed = segments
          .map((seg, idx) => {
            const isQuoted = idx % 2 === 1;
            if (isQuoted) {
              // Check if this looks like a module path (contains /, \, or @)
              const isPath =
                seg.includes("/") || seg.includes("\\") || seg.includes("@");
              if (isPath && seg.includes(BRAND_FROM)) {
                // Refuse: brand name in a module path
                refused = true;
                return seg;
              }
              if (isPath) {
                // Safe path (no brand name): don't transform
                return seg;
              }
              // Not a path: transform display strings as normal
              return seg.replaceAll(BRAND_FROM, BRAND_TO);
            }
            // Transform unquoted segments (identifiers, keywords, etc.)
            return seg.replaceAll(BRAND_FROM, BRAND_TO);
          })
          .join("");

        if (refused) {
          refusals.push(`${file}:${i + 1}`);
          return line;
        }

        if (CHECK && transformed !== line) {
          rebrandables.push(`${file}:${i + 1}`);
        }
        return CHECK ? line : transformed;
      }

      // Non-module-context lines: transform normally (including display strings).
      if (CHECK && line.includes(BRAND_FROM)) {
        rebrandables.push(`${file}:${i + 1}`);
      }
      return CHECK ? line : line.replaceAll(BRAND_FROM, BRAND_TO);
    })
    .join("\n");

  if (!CHECK && out !== src) {
    writeFileSync(file, out);
    changed++;
  }
}

// Refusal is non-atomic: other files/lines may already be rewritten on disk when this exits 1.
// Run this script only against a clean git tree, and `git checkout`/`reset` to recover if a refusal fires.
if (refusals.length) {
  refusals.forEach((loc) => console.error(`PATH HIT (would refuse): ${loc}`));
  process.exit(1);
}
if (CHECK) {
  if (rebrandables.length > 0) {
    rebrandables.forEach((loc) => console.error(`rebrandable: ${loc}`));
    process.exit(1);
  }
  console.log("--check: clean.");
} else {
  console.log(`Rebranded ${changed} file(s). Now run i18n extract/compile.`);
}
