// scripts/rebrand.mjs
// Fork rebrand: rewrites user-visible "Anarlog" strings to "Recap" across
// the desktop app source. Idempotent — safe to re-run after upstream merges.
// Never touches: import/require lines, lowercase functional ids/URLs,
// crates/, plugins/, package names.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const TARGET_DIR = join(ROOT, "apps/desktop/src");
const CHECK = process.argv.includes("--check");

const BRAND_FROM = "Anarlog";
const BRAND_TO = "Recap";

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) {
      if (name === "locales") continue; // regenerated by lingui, not edited
      yield* walk(p);
    } else if (/\.(ts|tsx)$/.test(name)) {
      yield p;
    }
  }
}

let changed = 0;
let remaining = 0;
const errors = [];

for (const file of walk(TARGET_DIR)) {
  const src = readFileSync(file, "utf8");
  if (!src.includes(BRAND_FROM)) continue;

  const out = src
    .split("\n")
    .map((line, i) => {
      if (!line.includes(BRAND_FROM)) return line;
      // Refuse to rewrite structural code references.
      if (/^\s*(import|export)\b.*\bfrom\b/.test(line) || /require\(/.test(line)) {
        errors.push(`${file}:${i + 1}: "${BRAND_FROM}" in an import/require line`);
        return line;
      }
      remaining += CHECK ? 1 : 0;
      return CHECK ? line : line.replaceAll(BRAND_FROM, BRAND_TO);
    })
    .join("\n");

  if (!CHECK && out !== src) {
    writeFileSync(file, out);
    changed++;
  }
}

if (errors.length) {
  console.error("Refused (fix manually):\n" + errors.join("\n"));
  process.exit(1);
}
if (CHECK) {
  if (remaining > 0) {
    console.error(`--check: ${remaining} rebrandable line(s) remain.`);
    process.exit(1);
  }
  console.log("--check: clean.");
} else {
  console.log(`Rebranded ${changed} file(s). Now run i18n extract/compile.`);
}
