// scripts/rebrand.mjs
// Fork rebrand: rewrites user-visible "Anarlog" strings to "Recap" across
// the desktop app source. Idempotent — safe to re-run after upstream merges.
// Never touches: import/require lines, lowercase functional ids/URLs,
// crates/, plugins/, package names.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const TARGET_DIR = join(ROOT, "apps/desktop/src");
const CHECK = process.argv.includes("--check");

const BRAND_FROM = "Anarlog";
const BRAND_TO = "Recap";

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) {
      if (name === "locales") continue; // regenerated by lingui, not edited
      yield* walk(p);
    } else if (/\.(ts|tsx)$/.test(name)) {
      yield p;
    }
  }
}

let changed = 0;
let remaining = 0;
const errors = [];

for (const file of walk(TARGET_DIR)) {
  const src = readFileSync(file, "utf8");
  if (!src.includes(BRAND_FROM)) continue;

  const out = src
    .split("\n")
    .map((line, i) => {
      if (!line.includes(BRAND_FROM)) return line;

      const isImportLine =
        /^\s*(import|export)\b.*\bfrom\b/.test(line) || /require\(/.test(line);

      if (isImportLine) {
        // Split on quoted strings: odd indices are quoted, even are unquoted.
        // Rename only in unquoted segments (identifiers), refuse if found in quotes (paths).
        const segments = line.split(/("[^"]*"|'[^']*')/);
        let refused = false;

        const transformed = segments
          .map((seg, idx) => {
            const isQuoted = idx % 2 === 1;
            if (isQuoted) {
              // Check if module path contains BRAND_FROM
              if (seg.includes(BRAND_FROM)) {
                refused = true;
              }
              return seg; // Don't transform quoted strings
            }
            // Transform unquoted segments (identifiers, keywords, etc.)
            return seg.replaceAll(BRAND_FROM, BRAND_TO);
          })
          .join("");

        if (refused) {
          errors.push(`${file}:${i + 1}: "${BRAND_FROM}" in an import/require path`);
          return line;
        }

        if (CHECK && transformed !== line) {
          remaining++;
        }
        return CHECK ? line : transformed;
      }

      // Non-import lines: transform normally.
      remaining += CHECK ? 1 : 0;
      return CHECK ? line : line.replaceAll(BRAND_FROM, BRAND_TO);
    })
    .join("\n");

  if (!CHECK && out !== src) {
    writeFileSync(file, out);
    changed++;
  }
}

if (errors.length) {
  console.error("Refused (fix manually):\n" + errors.join("\n"));
  process.exit(1);
}
if (CHECK) {
  if (remaining > 0) {
    console.error(`--check: ${remaining} rebrandable line(s) remain.`);
    process.exit(1);
  }
  console.log("--check: clean.");
} else {
  console.log(`Rebranded ${changed} file(s). Now run i18n extract/compile.`);
}
